---

- hosts: all
  become: true
  tasks:

  - name: install  updates (Ubuntu)
    apt:
        upgrade: dist
        update_cache: yes
    changed_when: false
    when: ansible_distribution == " Ubuntu"

- hosts: all
  become: true
  tasks:



  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH1BH8+OBHlD8a/GCyEjslqIFrPtxAk+ZGsEFsmFXXJx ansible"







- hosts: workstations
  become: true
  tasks:


  - name: install unzip
    package:
      name: unzip


  - name: install terraform
    unarchive:
       src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root







- hosts: web_servers
  become: true
  tasks:
  - name: install apache and php
    apt:
       name:
          -  apache2
          - libapache2-mod-php
       state: latest
       update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for syte
    tags: apache,apache2, httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644








